<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Deleting a Particle</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
<h1></h1>
<div></div>
<div></div>
<?php

    echo "List of Particles <br>";
    if (count($results)> 0) {

        foreach($results as $result) {
            echo "id: " . $result["id"] . " - Particle: " . $result["Particle"] . " " . "- Charge:" . $result["Charge"] . "<br>";
        }

    }

    if($delete_id != '')
    {
        echo "The particle with id " . $delete_id . " has been deleted!";
    }
?>
<form action="/delete" method="post">
    Type the ID of the particle you want to delete<input name="delete_orig" type="number"></input><button>Delete Particle</button>
</form>

</body>
</html>