<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Pete's Test App</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #2959dc;
                font-size: 18px;
            }

            h1 {
                color: #f10509;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                text-align: center;
                margin-bottom: 0;
            }
            h2 {
                color: #9e0600;
                letter-spacing: -1%px;
                font-family: 'Lato', sans-serif;
                font-size: 50%px;
                font-weight: 200;
                margin-bottom: 0;
             button {
                 color: #fdffff;
             }
            }
        </style>
    </head>
    <body>
        <h1>Pete's App</h1>
        <div></div>


        <?php if (isset($lastname)) : ?>
            <h2>Hello <?php echo $firstName . $lastname ?>!</h2>
        <?php else: ?>
            Try <a href="http://www.slimframework.com">SlimFramework</a>
        <?php endif; ?>
        <div></div>
         <form action="/lastname" method="get">
             What is your First Name:<input name="firstname" type="text"></input>
             <div></div>
             What is your Last Name:<input name="lastname" type="text"></input><button>Continue</button>
        </form>
    </body>
</html>
